#
# Deploy the web API which is the Orleans client
# 
# Requires:
# - Secret 'orleans-secrets' with key 'storageConnectionString' set to valid value
#

# ------------------- API Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: orleans-api
  labels:
    app: orleans-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orleans-api
  template:
    metadata:
      labels:
        app: orleans-api
    spec:
      containers:
      - name: orleans-api
        image: davidgri.azurecr.io/smilr-orleans/api:v1
        imagePullPolicy: Always

        ports:
        - containerPort: 4000

        env:     
        - name: Orleans__ClusterId
          value: smilr-kube
        - name: Orleans__SiloHost
          value: silo-gateway-svc
        - name: Orleans__ConnectionString
          valueFrom:
            secretKeyRef:
              name: orleans-secrets
              key: storageConnectionString

        resources:
          limits:
            memory: "1G"
            cpu: "0.3"

---

# ------------------- Loadbalancer for API ------------------- #

kind: Service
apiVersion: v1
metadata:
  name: data-api-svc
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app: orleans-api
