kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "smilr.fullname" . }}-data-api
  labels:
{{ include "smilr.labels" . | indent 4 }} 
spec:
  replicas: {{ .Values.dataApi.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "smilr.name" . }}-data-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "smilr.name" . }}-data-api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ include "smilr.name" . }}-data-api
 
        image: "{{ .Values.registryPrefix }}smilr/data-api:{{ .Values.dataApi.imageTag }}"
        imagePullPolicy: {{ .Values.dataApi.imagePullPolicy }}

        ports:
        - containerPort: 4000

        env:     
        - name: MONGO_CONNSTR
          value: {{ if .Values.dataApi.mongoConnStr }} {{ .Values.dataApi.mongoConnStr }} {{ else }} "mongodb://{{ .Release.Name }}-mongodb" {{ end }}

        - name: RELEASE_INFO
          value: 'Helm release: {{ .Release.Name }}, namespace: {{ .Release.Namespace }}, revision: {{ .Release.Revision }}, chart: {{ .Chart.Name }}-{{ .Chart.Version }}'

        {{ if .Values.sentiment.enabled }}
        - name: SENTIMENT_API_ENDPOINT
          value: http://{{ include "smilr.fullname" . }}-sentiment:5000
        {{ end }}
        {{ if (and .Values.sentiment.externalEndpoint .Values.sentiment.key) }}
        - name: SENTIMENT_API_ENDPOINT
          value: {{ .Values.sentiment.externalEndpoint }}
        - name: SENTIMENT_API_KEY
          value: {{ .Values.sentiment.key }}          
        {{ end }}

        {{ if .Values.dataApi.aadClientId }}
        - name: SECURE_CLIENT_ID
          value: {{ .Values.dataApi.aadClientId }}
        {{ end }}

        livenessProbe:
          httpGet:
            path: /api/info
            port: 4000
          initialDelaySeconds: 3
          periodSeconds: 20

        resources:
          requests:
            memory: "40M"
            cpu: "50m"
          limits:
            memory: "128M"
            cpu: "200m"
