apiVersion: v1
appVersion: "4.0"
description: A Helm chart to deploy Smilr microservices app to Kubernetes
name: smilr
version: 2.0.2
icon: https://github.com/benc-uk/smilr/blob/master/vue/public/favicon.png
maintainers: 
  - name: Ben Coleman
    email: ben.coleman@microsoft.com
home: https://github.com/benc-uk/smilr
sources:
  - https://github.com/benc-uk/smilr