registryPrefix: bcdemo.azurecr.io/
domainSuffix: smilr.f0dfafed36164c7faac0.westeurope.aksapp.io
cmCertIssuer: 

dataApi:
  imageTag: stable
  replicas: 5
  # Leave blank to use the internal service, override if using external database
  mongoConnStr: 
  imagePullPolicy: Always

frontend:
  imageTag: stable
  replicas: 5
  imagePullPolicy: Always

mongodb:
  persistence:
    enabled: true
  replicaSet:
    enabled: true